name: json_ld_processor
description: JSON-LD Processor according to JSON-LD Processing API 1.1 with support for URDNA2015 normalization.
version: 1.0.2
repository: https://github.com/b2cm/json_ld_procossor

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  http: ^0.13.4
  crypto: ^3.0.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
